import React from 'react';
import { BadgeIndianRupee, BrainCircuit, CalendarDays, CheckCircle2, HeartHandshake, Hotel, Landmark, LockKeyhole, MapPinned, ShieldCheck, Sparkles, Ticket, Train, UserRoundCheck, Users } from 'lucide-react';
import { InfoCard, StaticJourneyLayout } from '../components/StaticJourneyLayout';

const images = {
  offers: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCdeWPryGpegxSQ_5ijLc-vEsNl_47Wg3hKH2FXSLDycUlWyV5-WhR23JB5LTM905rfgiVCHV7QhOIIfDGtZHxWyE-MO22YWxXMPB-_Sq5qnzLrlPzyFlrHe0xD26E6RgubhibZQ6zCQqtB7kRHp79xC_cQn8feXeLrKtGv7GsSDd7EErBVheUKjVuYs4_5v89zrpT3--MLXRg0SQYjWqcJN0TfuVPVX8Ko9Ax1uaSQEiPJXf-hcdNhqbJhEkxgwKbKMGcNC6ujYHs',
  feedback: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCx_ax93bg277wVe6uMv9cTFrfAmA2SEYwM3n42uRQv1LvALJbmnhQ9TsoONrn3xPxru7Qc3A-qKyi8a8WFx-CYxeXg_cT6itKLfmRj9j1zgkJuIgmhoGjD0R7GtN1sW18TTwNMo2pJVCbQWtLwnHAYZQfnGaWbenuyGAU7GWdR-cw2zdTFKkeJz6QbUQ8NwrxuQyo8eYJFZZ5hXMBUvkE_fwvQ_S69T_6gTiog2ekuqN_KPU2yTri5owBuOHMUkgveZ785l5rM_c8',
  impact: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB_unM9uRc5jvMYHE-ivK_2e1kKOcpelDTrgq0f7W-zRTbyU_YdeLRfOT11vfXAE2cgbs4ZqeYenhdLTkvRapc7_H83UktLUEU9m7Y-w7nASXp--WCKsGGeXTr0KAuVaCItJpWjzv88NjIOjwIHEncAtfg6O4qIY4_HxmkAflxdcCR7FM1O73A11VQaOlmWI4EsHL5KeWiskREQ8FuzY7tuDNYTsmBh9wsERYxOLzBw8f9B3mq0ngBA-tmMVxCSEACevKl9esu4w0o',
  summary: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDzOleTszeTz22BE85VzLZEl1zot3YisCX0u_9SOyx119_lNJfx54I05OZbNZHf7-fbR-vm6gtCbRHnj-fPx6EDW_RM8ap0BWD9sY8yuD3IPb7u2Gy0VHWGkQb_V-bW3e8_6MS-kduU1tOZSG95If1OhkVERgn1hNPRBI7zHElvpD2DR_WtNqjyCEGRUHP7PB06qB7nuxFRG3pXueqHCuXuS-5TW-CMdi0U_L7Qt3034BxNp9cqQGYidt5vFXGHtkZxhcCMq51MrZU',
  security: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBvbZePfCIhhdcQyYpunbNmc1ILgu4AkCGKsHUe3iRzgwPTqWEptG4DlXH5FXAwc4asvCnO9-i5wI3vC29ndAwCIe9HOXQLBatm_jdRxwfBIzS9aWUoFCq7VJa0o1kkHkibwCsgjPDEmt2Asu-d4RdPCIL4Q7pC2GSEaJDpnIsxz_UuVt2b9axrdpKWpUny7OHie1YsJW3c0KNxU8aFhvgN8gO7ydORO0wrSmGxzfdsOA1S-H2gY0ID-wNceEVUzbPpEMGfOwXdifY'
};

export const OffersInfoPage = () => <StaticJourneyLayout backgroundImage={images.offers} eyebrow="Offers & Banking Incentives" title="Exclusive Journey Benefits" intro="A clear overview of the savings and partner benefits available with JanYatri."><div className="grid gap-5 md:grid-cols-3"><InfoCard icon={BadgeIndianRupee} title="10% Cashback">Earn up to 10% cashback on eligible bookings made through selected payment partners.</InfoCard><InfoCard icon={Ticket} title="₹300 Travel Credit">A travel credit can be applied to qualifying journeys, stays, and local experiences.</InfoCard><InfoCard icon={Sparkles} title="Extra 5% Off">Selected partner journeys include an additional seasonal saving for JanYatri travellers.</InfoCard></div></StaticJourneyLayout>;

export const RecommendationPage = () => <StaticJourneyLayout eyebrow="AI Journey Recommendation" title="A smarter way to choose your journey" intro="This recommendation balances affordability, travel time, and comfort for a Delhi to Varanasi trip."><div className="mx-auto grid max-w-4xl gap-5 md:grid-cols-3"><InfoCard icon={BrainCircuit} title="Best overall value" accent>Moderate budget and comfort preferences point to a balanced itinerary with reliable connections.</InfoCard><InfoCard icon={Train} title="Travel plan">A comfortable rail-first route with practical local transfers keeps the journey simple.</InfoCard><InfoCard icon={CalendarDays} title="Why it fits">A well-paced schedule leaves room for heritage visits without overloading each day.</InfoCard></div></StaticJourneyLayout>;

export const FeedbackPage = () => <StaticJourneyLayout backgroundImage={images.feedback} eyebrow="Feedback & Survey" title="Your journey experience matters" intro="JanYatri uses traveller feedback to make planning clearer, safer, and more useful."><div className="mx-auto grid max-w-4xl gap-5 md:grid-cols-3"><InfoCard icon={HeartHandshake} title="Thoughtful planning">Feedback helps us refine the information shown at each stage of a journey.</InfoCard><InfoCard icon={Users} title="Better local discovery">Traveller perspectives help surface relevant stays, routes, and local experiences.</InfoCard><InfoCard icon={CheckCircle2} title="Continuous improvement">Every insight contributes to a more reliable and accessible travel experience.</InfoCard></div></StaticJourneyLayout>;

export const ImpactPage = () => <StaticJourneyLayout backgroundImage={images.impact} eyebrow="Impact & Future Vision" title="Travel that strengthens local communities" intro="JanYatri is designed to make journeys more connected while helping local tourism benefit more people."><div className="grid gap-5 md:grid-cols-3"><InfoCard icon={Landmark} title="Local businesses">Visibility for local accommodation, food, transport, and small tourism enterprises.</InfoCard><InfoCard icon={MapPinned} title="Local guides">Meaningful discovery that highlights knowledgeable guides and regional stories.</InfoCard><InfoCard icon={HeartHandshake} title="Local artisans">A platform for travellers to discover the crafts and culture that make each place unique.</InfoCard></div></StaticJourneyLayout>;

export const TripSummaryPage = () => <StaticJourneyLayout backgroundImage={images.summary} eyebrow="Trip Summary / Ticket" title="Your journey is ready" intro="Everything you need for your trip, presented in one easy-to-read overview."><div className="mx-auto grid max-w-4xl gap-5 md:grid-cols-2"><InfoCard icon={Train} title="Journey details"><p><strong>Volvo Bus</strong> · ₹600</p><p className="mt-2"><strong>Heritage Stay</strong> · 3 Nights · ₹3,600</p><p className="mt-2"><strong>Experiences</strong> · Ram Mandir visit, heritage walk, and Ganga / Sarayu experience</p></InfoCard><InfoCard icon={UserRoundCheck} title="Traveller details"><p><strong>Passenger:</strong> Vaibhav</p><p className="mt-2"><strong>Passenger ID:</strong> JY-10482</p><p className="mt-2"><strong>Trip ID:</strong> JY-AYO-2026-0918</p><div className="mt-5 border-t border-slate-200 pt-4 text-lg font-black text-[#fd9000]">Estimated Total · ₹5,400</div></InfoCard></div></StaticJourneyLayout>;

export const SecurityPrivacyPage = () => <StaticJourneyLayout backgroundImage={images.security} eyebrow="Security & Privacy" title="Your journey. Your data. Your control." intro="JanYatri is designed to keep travel information secure while giving travellers clear control over what they share."><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4"><InfoCard icon={UserRoundCheck} title="Secure Passenger ID">Manage journey details without repeatedly sharing personal information.</InfoCard><InfoCard icon={ShieldCheck} title="Data Protection">Travel and profile information is handled with secure data practices.</InfoCard><InfoCard icon={LockKeyhole} title="Encrypted Communication">Sensitive information is designed to be transmitted securely.</InfoCard><InfoCard icon={CheckCircle2} title="Privacy Control">Choose the information you provide and how it supports your journey.</InfoCard></div></StaticJourneyLayout>;
